StoreApp/Controllers/OrderController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IServiceManager _manager;
        private readonly Card _card;

        public OrderController(IServiceManager manager, Card card)
        {
            _manager = manager;
            _card = card;
        }
        public ViewResult Checkout() => View(new Order());

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Checkout([FromForm] Order order)
        {
            if (_card.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your card is empty");
            }
            if (ModelState.IsValid)
            {
                order.Lines = _card.Lines.ToArray();
                _manager.OrderService.SaveOrder(order);
                _card.Clear();
                return RedirectToPage("/Complete", new { OrderId = order.OrderId });
            }
            else
            {
                return View();
            }
        }
    }
}

StoreApp/Pages/Card.cshtml.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.Contracts;
using StoreApp.InfraStructure.Extensions;

namespace StoraApp.Pages
{
  public class CardModel : PageModel
  {
    private readonly IServiceManager _manager;
    public Card Card { get; set; } //IoC
    public string ReturnUrl { get; set; } = "/";

    public CardModel(IServiceManager manager, Card cartService)
    {
      _manager = manager;
      Card = cartService;
    }

    public void OnGet(string returnUrl)
    {
      ReturnUrl = returnUrl ?? "/";
      //  Card = HttpContext.Session.GetJson<Card>("card") ?? new Card();
    }

    public IActionResult OnPost(int productId, string returnUrl)
    {
      Product? product = _manager.ProductService.GetOneProduct(productId, false);

      if (product is not null)
      {
        //  Card = HttpContext.Session.GetJson<Card>("card") ?? new Card();
        Card?.AddItem(product, 1);
        //  HttpContext.Session.SetJson<Card>("card", Card);
      }
      return RedirectToPage(new { returnUrl = returnUrl }); //returnUrl
    }

    public IActionResult OnPostRemove(int id, string returnUrl)
    {
      //  Card = HttpContext.Session.GetJson<Card>("card") ?? new Card();
      Card?.RemoveLine(Card.Lines.First(cl => cl.Product.ProductId.Equals(id)).Product);
      //  HttpContext.Session.SetJson<Card>("card", Card);
      return Page();
    }
  }
}

StoreApp/Pages/Demo.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StoraApp.Pages
{
    public class DemoModel : PageModel
    {
        public String? FullName => HttpContext?.Session?.GetString("name")?? "";
        public void OnGet()
        {
        }
        public void OnPost([FromForm] string name)
        {
            //  FullName = name;
            HttpContext.Session.SetString("name", name);
        }
    }
}

StoreApp/Pages/Card.cshtml
@page "/Card"
@model CardModel

@{
    Layout = "_LayoutCard";
}

<div>
    <div class="display-6 text-center">
        Card
    </div>
    <table>
        <thead>
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Subtotal</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.Card?.Lines ?? Enumerable.Empty<CardLine>())
            {
                <tr>
                    <td>@line.Product.ProductName</td>
                    <td>@line.Quantity</td>
                    <td>@line.Product.Price.ToString("c")</td>
                    <td>@((line.Product.Price * line.Quantity).ToString("c2"))</td>
                    <td>
                        <form method="post" asp-page-handler="Remove">
                            <input type="hidden" name="id" value="@line.Product.ProductId" />
                            <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                            <button type="submit" class="btn btn-sm btn-danger">
                                <i class="fa-solid fa-trash"></i> Remove
                            </button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4" class="text-right"> Total : </td>
                <td class=" text-right" style="color: red;">@Model.Card?.ComputeTotalValue().ToString("c2")</td>
            </tr>
        </tfoot>
    </table>
    <div class="text-center my-3">
        <div class="btn-group">
            <a class="btn btn-primary get-home" href="@Model.ReturnUrl">Continue Shopping</a>
            <a class="btn btn-primary mx-2 get-home" asp-action="Checkout" asp-controller="Order">Checkout</a>
        </div>
    </div>
</div>

StoreApp/Pages/Complete.cshtml
@page

@{
    Layout ="_LayoutComplete";
}

<div class="text-center">
    <div class="display-6" style="color: red; font-size: 40px; margin-top: 30px;">THANKS!</div>
    <p style="margin-top: 10px;">Thanks for placing order #@OrderId</p>
    <p style="margin-top: 10px;"> We'll ship your orders as soon as possible</p>
    <a class="btn btn-primary" asp-controller="Home" asp-action="Index">Return to Store</a>
</div>

@functions
{
    [BindProperty(SupportsGet = true)]
    public String? OrderId { get; set; }
}

StoreApp/Pages/Contact.cshtml
@page "/getintouch"

@{
    Layout="_LayoutContact";
}

<div class="text-center ">
    <div class="row">
        <div class="left-side col-md-6" style="margin: 20px 20px auto -50px;">
            <div class="display-6">Contact</div>
            <div class="lead">
                <i class="fa fa-phone text-primary"></i>
                <p>
                    ALO 128 BTK Akademi Bilgi ve Destek Hattı
                </p>
                <div class="display-6">Address</div>
                <i class="fa-solid fa-address-book text-primary"></i>
                <p>
                    destek@btkakademi.gov.tr
                </p>
                <div class="display-6">E-mail</div>
                <i class="fa-solid fa-envelope text-primary"></i>
                <p>
                    Bilgi Teknolojileri ve İletişim Kurumu Eskişehir Yolu 10.Km
                    No: 276 Posta Kodu: 06530 Çankaya/Ankara
                </p>
            </div>
        </div>
        <div class="right-side col-md-6" style="margin: 20px -20px; auto 20px">
            <iframe
                src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d6121.026854043178!2d32.751985!3d39.907525!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48d1cf828cb6c5c7%3A0x983f31be2f30bfc6!2sSinoma%20Overseas!5e0!3m2!1str!2sus!4v1723538462910!5m2!1str!2sus"
                width="550" height="400" style="border:5;" allowfullscreen="" loading="lazy"
                referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
    </div>
</div>
</div>

StoreApp/Pages/Demo.cshtml
@page
@model StoraApp.Pages.DemoModel

<div class="my-5 text-center">
    <div class="display-6 my-3">Welcome @Model?.FullName</div>
    <form method="post" asp-page="/demo">
        <div class="form-group">
            <input class="form-control my-2" name="name" placeholder="Enter Your Name" style="border-color: black;" />
            <input type="submit" class=" btn btn-primary my-2" />
        </div>
    </form>
</div>