StoreApp/Components/CardSummaryViewComponent.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Components
{
    public class CardSummaryViewComponent : ViewComponent
    {
        private readonly Card _card;

        public CardSummaryViewComponent(Card cardService)
        {
            _card = cardService;
        }

        public string Invoke()
        {
            return _card.Lines.Count().ToString();
        } 
    }
}

StoreApp/Components/ProductSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Components
{
    public class ProductSummaryViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;

        public ProductSummaryViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }

        public string Invoke()
        {
            //service
            return _manager.ProductService.GetAllProducts(false).Count().ToString();
            // ürün sayısını alıyoruz
        }
    }
}

StoreApp/Controllers/CategoryController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;

namespace StoraApp.Controllers
{
    public class CategoryController : Controller
    {
        private IRepositoryManager _manager;

        public CategoryController(IRepositoryManager manager)
        {
            _manager = manager;
        }
        public IActionResult Index()
        {
            var model = _manager.Category.FindAll(false);
            return View(model);
        }
    }
}

StoreApp/Controllers/ProductController.cs
using Entities.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;
using Services.Contracts;
using StoreApp.Models;

namespace StoraApp.Controllers
{
    public class ProductController : Controller
    {
        // DI (Dependency of Injection) çerçevesi
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        // DI (Dependency of Injection) çerçevesi

        public /*IEnumerable<Product>*/ IActionResult Index(ProductRequestParameters p)
        {
            /* var context = new RepositoryContext(
                new DbContextOptionsBuilder<RepositoryContext>().UseSqlite("Data Source = C:\\Users\\ozgun\\source\\GitHub\\MVC\\Store\\ProductDb.db").Options // DI olmazsa bunu yazmak zorundayız 
             ); */
            var products = _manager.ProductService.GetAllProductsWithDetails(p);
            var pagination = new Pagination()
            {
                CurrentPage = p.PageNumber,
                ItemsPerPage = p.PageSize,
                TotalItems = _manager.ProductService.GetAllProducts(false).Count()
            };
            return View(new ProductListViewModel()
            {
                Products = products,
                Pagination = pagination
            });
        }

        public IActionResult Get([FromRoute(Name = "id")] int id)
        {
            var model = _manager.ProductService.GetOneProduct(id, false);
            // Product product = _context.Products.First(p => p.ProductId.Equals(id));
            return View(model);
        }
    }
}

StoreApp/Views/Shared/_Footer.cshtml
<div class="bg-light border-top p-3">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="lead text-center ">
                    <i class="fa-solid fa-store text-secondary display-6"></i>
                    <br />
                    <bold>BTK</bold> Akademi
                </div>
                <div class="text-muted text-center">
                    Store App
                </div>
            </div>
            <div class="col-md-8">
                <div class="text-center text-muted my-3">
                    &copy; 2023 <br />BTK Akademi ASP.NET Core MVC Eğitimi
                </div>

                <div class="text-center">
                    <div class="btn-group">
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-facebook"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-twitter"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-linkedin"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-youtube"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-instagram"></i>
                        </a>
                    </div>
                </div>

            </div>
            <div class="col-md-2">
                <div products="" number="6"></div>
            </div>
        </div>
    </div>
</div>

StoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StoreApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css.css" />
</head>
<body>
    <header>
        <partial name="_Navbar" />
        @RenderSection("Header", false)
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer>
        @RenderSection("Footer", false)
        <partial name="_Footer"></partial>
    </footer>

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.js.map"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    <script src="~/js/site.js"></script>

    @await RenderSectionAsync("Script", required: false)
</body>
</html>

StoreApp/Views/Shared/_LayoutCard.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Card</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css.css" />
</head>
<body>
    <header>
        <partial name="_Navbar" />
        @RenderSection("Header", false)
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer>
        @RenderSection("Footer", false)
    </footer>

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.js.map"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    <script src="~/js/site.js"></script>

    @await RenderSectionAsync("Script", required: false)
</body>
</html>

StoreApp/Views/Shared/_LayoutCheckout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Checkout</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css.css" />
</head>
<body>
    <header>
        <partial name="_Navbar" />
        @RenderSection("Header", false)
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer>
        @RenderSection("Footer", false)
    </footer>

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.js.map"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    <script src="~/js/site.js"></script>

    @await RenderSectionAsync("Script", required: false)
</body>
</html>

StoreApp/Views/Shared/_LayoutComplete.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Complete</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css.css" />
</head>
<body>
    <header>
        <partial name="_Navbar" />
        @RenderSection("Header", false)
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer>
        @RenderSection("Footer", false)
    </footer>

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.js.map"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    <script src="~/js/site.js"></script>

    @await RenderSectionAsync("Script", required: false)
</body>
</html>

StoreApp/Views/Shared/_LayoutContact.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css.css" />
</head>
<body>
    <header>
        <partial name="_Navbar" />
        @RenderSection("Header", false)
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer>
        @RenderSection("Footer", false)
    </footer>

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.js.map"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    <script src="~/js/site.js"></script>

    @await RenderSectionAsync("Script", required: false)
</body>
</html>

StoreApp/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar bg-primary navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
    <div class="container-fluid">
        <a id="storeapp" class="navbar-brand" href="/" style="padding-bottom: 6px;"><i class="fa-solid fa-store fa-2x text-secondary"></i></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item"></li>
                <a id="home" class="nav-link active" aria-current="page" asp-controller="Home"
                    asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a id="products" class="nav-link" aria-current="page" asp-controller="Product"
                        asp-action="Index">Product (@await Component.InvokeAsync("ProductSummary"))  </a>
                </li>
                <li class="nav-item">
                    <a id="products" class="nav-link" aria-current="page" asp-controller="Category"
                        asp-action="Index">Categories</a>
                </li>
                <li class="nav-item">
                    <a id="products" class="nav-link" aria-current="page" asp-page="/Contact">Contact</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" id="admin" target="_blank" aria-current="page" asp-area="" asp-page="/Card"><i
                            class="fa-solid fa-cart-shopping"></i> Card (@await Component.InvokeAsync("CardSummary"))</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="admin" target="_blank" aria-current="page" asp-area="Admin"
                        asp-controller="Dashboard" asp-action="Index">Admin</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

StoreApp/Views/Shared/_ProductCard.cshtml
@model Product


<div class="col-sm-12 col-md-4 my-2 product-grid">
    <div class="items">
        <div class="card-header text-center"
            style="font-size: 20px; font-weight: bold; color: black; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;">
            @Model?.ProductName
        </div>
        <img src="@Model?.ImageUrl" class="card-img-top" alt="Technology">
        <div class="card-body ">
            <div class="card-text">
                <div class="text-center lead p-2 rounded-2" style="color: red;font-weight: bold;">
                    @Model?.Price.ToString("c")
                </div>
            </div>
            <p class="card-text">@Model?.Summary</p>
            <div class="d-flex justify-content-center">
                <div class="btn btn-group">
                    <a class="btn btn-info productButtun" asp-action="Get" asp-route-id="@Model?.ProductId"
                        style="width: 70px;"><i class="fa-solid fa-arrow-right"></i></a>
                    <form id="@Model?.ProductId" asp-page="/card" method="post">
                        <input type="hidden" asp-for="ProductId" />
                        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                        <button type="submit" class="btn btn btn-dark productButtun" style="width: 70px;">
                            <i class="fa fa-cart-plus"></i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>