StoreApp/Components/ProductSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Components
{
    public class ProductSummaryViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;

        public ProductSummaryViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }

        public string Invoke()
        {
            //service
            return _manager.ProductService.GetAllProducts(false).Count().ToString();
            // ürün sayısını alıyoruz
        }
    }
}

StoreApp/Controllers/CategoryController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;

namespace StoraApp.Controllers
{
    public class CategoryController : Controller
    {
        private IRepositoryManager _manager;

        public CategoryController(IRepositoryManager manager)
        {
            _manager = manager;
        }
        public IActionResult Index()
        {
            var model = _manager.Category.FindAll(false);
            return View(model);
        }
    }
}

StoreApp/Controllers/OrderController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IServiceManager _manager;
        private readonly Card _card;

        public OrderController(IServiceManager manager, Card card)
        {
            _manager = manager;
            _card = card;
        }
        public ViewResult Checkout() => View(new Order());

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Checkout([FromForm] Order order)
        {
            if (_card.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your card is empty");
            }
            if (ModelState.IsValid)
            {
                order.Lines = _card.Lines.ToArray();
                _manager.OrderService.SaveOrder(order);
                _card.Clear();
                return RedirectToPage("/Complete", new { OrderId = order.OrderId });
            }
            else
            {
                return View();
            }
        }
    }
}

StoreApp/Controllers/ProductController.cs
using Entities.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;
using Services.Contracts;
using StoreApp.Models;

namespace StoraApp.Controllers
{
    public class ProductController : Controller
    {
        // DI (Dependency of Injection) çerçevesi
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        // DI (Dependency of Injection) çerçevesi

        public /*IEnumerable<Product>*/ IActionResult Index(ProductRequestParameters p)
        {
            /* var context = new RepositoryContext(
                new DbContextOptionsBuilder<RepositoryContext>().UseSqlite("Data Source = C:\\Users\\ozgun\\source\\GitHub\\MVC\\Store\\ProductDb.db").Options // DI olmazsa bunu yazmak zorundayız 
             ); */
            var products = _manager.ProductService.GetAllProductsWithDetails(p);
            var pagination = new Pagination()
            {
                CurrentPage = p.PageNumber,
                ItemsPerPage = p.PageSize,
                TotalItems = _manager.ProductService.GetAllProducts(false).Count()
            };
            return View(new ProductListViewModel()
            {
                Products = products,
                Pagination = pagination
            });
        }

        public IActionResult Get([FromRoute(Name = "id")] int id)
        {
            var model = _manager.ProductService.GetOneProduct(id, false);
            // Product product = _context.Products.First(p => p.ProductId.Equals(id));
            return View(model);
        }
    }
}

StoreApp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ADMIN PANEL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css.css" />
</head>
<body>
    <header>
        <partial name="_Navbar" />
        @RenderSection("Header", false)
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer>
        @RenderSection("Footer", false)
    </footer>

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.js.map"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    <script src="~/js/site.js"></script>

    @await RenderSectionAsync("Script", required: false)
</body>
</html>

StoreApp/Areas/Admin/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg" style="background-color: #000000;">
    <div class="container-fluid">
        <a class="navbar-brand text-white" href="/" style="padding-bottom: 6px;">Admin</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarNavAltMarkup">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a id="home" class="nav-link text-white active" aria-current="page" asp-controller="Dashboard"
                        asp-action="Index">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a id="products" class="nav-link text-white active" asp-controller="Product" asp-action="Index">Product
                        @* (@await Component.InvokeAsync("ProductSummary")) *@ </a>
                </li>
                <li class="nav-item">
                    <a id="products" class="nav-link text-white active" asp-controller="Category"
                        asp-action="Index">Categories</a>
                </li>
                <li class="nav-item">
                    <a id="products" class="nav-link text-white active" asp-controller="Order"
                        asp-action="Index">Orders</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a target="_blank" id="products" class="nav-link text-white active" asp-area="" asp-controller="Home"
                        asp-action="Index">Web</a>
                </li>
            </ul>
        </div>
    </div>
</nav>